### ISSUE TITLE
Requirement Elicitation from Statement of Work for the SUS - SherinePaulRaj

### ISSUE THREAD

**Issue by sandeepkumar1709** [sandeepkumar1709/smarter-university-system#15]
Task #7 
Sherine should gather the list of requirements from the Statement of Work for the SUS.

**Comment by SherinePaulRaj** [comment]
The Requirements for the noun Instructor are elicited from the given SOW for SUS and stated below:

1. Instructors should be able to edit the syllabus page for their class.
2. Instructors should have access to a dashboard showing student details (grades etc).
3. Instructors should receive notifications when students submit requests for their classes.
4. Instructors should be able to view academic records of individual students enrolled in their class.
5. Instructors should have the ability to export or download class attendance records and grade sheets.
6. Instructors should be able to communicate with enrolled students through the SUS platform.
