### ISSUE TITLE
Review the requirements by Voohitha

### ISSUE THREAD

**Issue by sandeepkumar1709** [sandeepkumar1709/smarter-university-system#17]
Task for #7 
Voohitha ought to review the requirements of her colleagues.

**Comment by Voohitha-hub** [comment]
I have thoroughly reviewed my teammates’ requirements and engaged in necessary discussions. Based on the feedback received, I have finalized the following requirements.

1. The student must be presented with the course identifier and title for each available class by the system.
2. The student must be shown the name of the instructor responsible for teaching each class.
3. The student must be granted access to the class syllabus page, which contains the course syllabus and topics that will be covered.
4. The student must be able to enroll in classes that have available slots, and should receive immediate confirmation upon successful enrollment.
5. The student must be able to view the dates of lectures for each class.
6. The student must be furnished with an option to attend lectures remotely via video conferencing.
7. The student must be showcased the assigned team and team members for each group project or team assignment.
8. The student must be permitted to view all their grades for the semester, encompassing grades for assignments, quizzes, and exams.
