### ISSUE TITLE
Create a Binary Tree for prioritizing requirements  - Voohitha

### ISSUE THREAD

**Issue by sandeepkumar1709** [sandeepkumar1709/smarter-university-system#21]
Task for https://github.com/sandeepkumar1709/smarter-university-system/issues/8
After gathering the list of requirements, Voohitha should draw a Binary tree representing each requirement in assigning priorities.

**Comment by Voohitha-hub** [comment]
I have drawn a binary tree for all the stack of requirements gathered by team. Below is the tree created using the Graphviz tool.

digraph G {
  1->2;
  1->4;
  2->3;
  2->9;
  3->8;
  3->25;
  8->10;
  8->12;
  10->16;
  10->11;
  16->L16;
  16->22;
  22->24;
  22->23;
  11->13;
  11->27;
  13->20;
  13->R13;
  20->21;
  20->R20;
  21->31;
  21->26;
  26->28;
  26->R26;
  28->29;
  28->R28;
  27->30;
  27->R27;
  9->18;
  9->14;
  14->17;
  14->R14;
  18->L18;
  18->19;
  4->6;
  4->5;
  6->7;
  6->R6;
  7->L7;
  7->15;
}
