### ISSUE TITLE
Discussion on User Stories

### ISSUE THREAD

**Issue by Voohitha-hub** [sandeepkumar1709/smarter-university-system#24]
Let's set up a call and discuss if the user stories are meeting all the characteristics.

**Comment by sandeepkumar1709** [comment]
summary of today's meeting.

We have compiled a list of top user stories and added them to the 'Final Merged' tab in Microsoft Excel. By today, we review and address any issues with these user stories in the WhatsApp group immediately. We need to complete the review of all user stories by the end of the day and confirm them in the WhatsApp group. 

Tomorrow, we will start prioritizing the user stories, and the day after, we will draw a graph before the class. This way, we can review each other's graphs after the class physically
